import streamlit as st
import pandas as pd
import pandas_ta as ta
import datetime
import os

# --- DATABASES ---
@st.cache_data
def load_fno_base_stocks():
    if os.path.exists("nse_fno_stocks.csv"):
        try:
            df = pd.read_csv("nse_fno_stocks.csv")
            return [t for t in df['SYMBOL'].dropna().unique()]
        except: return ["NIFTY", "BANKNIFTY", "RELIANCE"]
    return ["NIFTY", "BANKNIFTY", "RELIANCE", "HDFCBANK", "TCS", "INFY", "ITC", "SBI"]

fno_base_universe = load_fno_base_stocks()

def get_spot_symbol(sym):
    if sym == "NIFTY": return "NSE:NIFTY50-INDEX"
    elif sym == "BANKNIFTY": return "NSE:NIFTYBANK-INDEX"
    return f"NSE:{sym}-EQ"

# --- FYERS API FETCHER ---
def fetch_historical_data(fyers, symbol, resolution, days_back):
    now = datetime.datetime.now()
    range_from = (now - datetime.timedelta(days=days_back)).strftime("%Y-%m-%d")
    range_to = now.strftime("%Y-%m-%d")
    data = {"symbol": symbol, "resolution": str(resolution), "date_format": "1", "range_from": range_from, "range_to": range_to, "cont_flag": "1"}
    response = fyers.history(data=data)
    if response.get("s") == "ok" and response.get("candles"):
        df = pd.DataFrame(response["candles"], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df['datetime'] = pd.to_datetime(df['timestamp'], unit='s') + pd.Timedelta(hours=5, minutes=30)
        df.set_index('datetime', inplace=True)
        return df
    return None

# --- DIXON TRADING VIEW STRATEGY LOGIC ---
def run_dixon_backtest(df):
    """Translated from User's TradingView Pine Script"""
    
    # 1. Calculate Indicators
    df.ta.supertrend(length=10, multiplier=3.0, append=True)
    df.ta.vwap(append=True)
    df.ta.atr(length=14, append=True)
    
    # Find dynamic column names generated by pandas_ta
    st_dir_col = [c for c in df.columns if c.startswith('SUPERTd')][0]
    st_val_col = [c for c in df.columns if c.startswith('SUPERT_')][0]
    
    # 2. Extract Time & Day Features
    df['dayofweek'] = df.index.dayofweek # 0=Mon, 1=Tue, ...
    df['hour'] = df.index.hour
    df['minute'] = df.index.minute
    
    df.dropna(inplace=True)

    in_trade = False
    trade_type = None
    entry_price = 0
    atr_at_entry = 0
    highest_seen = 0
    lowest_seen = 0
    trail_active = False
    trail_sl = 0
    
    trade_log = []
    equity_curve = [0]
    cumulative_pnl = 0
    
    prev_st_dir = 0

    for index, row in df.iterrows():
        # Current values
        close, high, low = row['close'], row['high'], row['low']
        vwap, atr = row['VWAP_D'], row['ATRr_14']
        st_dir = row[st_dir_col] # 1 is Bullish (Pine -1), -1 is Bearish (Pine 1)
        
        # Filters
        is_tuesday = row['dayofweek'] == 1
        is_afternoon = (row['hour'] > 12) or (row['hour'] == 12 and row['minute'] >= 30)
        is_morning = not is_afternoon
        
        trade_allowed = not is_tuesday

        # --- EXIT LOGIC (Checked First if inside a trade) ---
        if in_trade:
            if trade_type == "LONG":
                highest_seen = max(highest_seen, high)
                
                # Activate Trail if Breakeven Trigger Hit (1.0 ATR)
                if not trail_active and highest_seen >= entry_price + (1.0 * atr_at_entry):
                    trail_active = True
                    
                if trail_active:
                    trail_sl = highest_seen - (1.0 * atr_at_entry)
                
                # 1. Hard SL (Close below VWAP or ST Flips Bearish)
                if close < vwap or st_dir == -1:
                    pnl = close - entry_price
                    cumulative_pnl += pnl
                    trade_log.append({"Date": index, "Type": "LONG", "Entry": entry_price, "Exit": close, "PnL": pnl, "Exit Reason": "Hard SL/Flip"})
                    in_trade = False
                    
                # 2. Trailing SL Hit
                elif trail_active and low <= trail_sl:
                    pnl = trail_sl - entry_price
                    cumulative_pnl += pnl
                    trade_log.append({"Date": index, "Type": "LONG", "Entry": entry_price, "Exit": trail_sl, "PnL": pnl, "Exit Reason": "Trailing SL"})
                    in_trade = False
                    
            elif trade_type == "SHORT":
                lowest_seen = min(lowest_seen, low)
                
                # Activate Trail if Breakeven Trigger Hit (1.0 ATR)
                if not trail_active and lowest_seen <= entry_price - (1.0 * atr_at_entry):
                    trail_active = True
                    
                if trail_active:
                    trail_sl = lowest_seen + (1.0 * atr_at_entry)
                
                # 1. Hard SL
                if close > vwap or st_dir == 1:
                    pnl = entry_price - close
                    cumulative_pnl += pnl
                    trade_log.append({"Date": index, "Type": "SHORT", "Entry": entry_price, "Exit": close, "PnL": pnl, "Exit Reason": "Hard SL/Flip"})
                    in_trade = False
                    
                # 2. Trailing SL Hit
                elif trail_active and high >= trail_sl:
                    pnl = entry_price - trail_sl
                    cumulative_pnl += pnl
                    trade_log.append({"Date": index, "Type": "SHORT", "Entry": entry_price, "Exit": trail_sl, "PnL": pnl, "Exit Reason": "Trailing SL"})
                    in_trade = False
            
            equity_curve.append(cumulative_pnl)
            prev_st_dir = st_dir
            continue

        # --- ENTRY LOGIC ---
        st_buy_signal = (st_dir == 1) and (prev_st_dir == -1)
        st_sell_signal = (st_dir == -1) and (prev_st_dir == 1)
        
        # LONG ENTRY (Supertrend Buy + Above VWAP + Not Tuesday + PM Session)
        long_condition = st_buy_signal and (close > vwap) and trade_allowed and is_afternoon
        
        # SHORT ENTRY (Supertrend Sell + Below VWAP + Not Tuesday + AM Session implied)
        short_condition = st_sell_signal and (close < vwap) and trade_allowed and is_morning
        
        if long_condition:
            in_trade = True
            trade_type = "LONG"
            entry_price = close
            atr_at_entry = atr
            highest_seen = close
            trail_active = False
            
        elif short_condition:
            in_trade = True
            trade_type = "SHORT"
            entry_price = close
            atr_at_entry = atr
            lowest_seen = close
            trail_active = False
            
        equity_curve.append(cumulative_pnl)
        prev_st_dir = st_dir

    return pd.DataFrame(trade_log), equity_curve

# --- UI RENDERER ---
def render_ui(fyers):
    st.markdown("### ⏳ The Dixon Strategy Time Machine")
    st.write("Running your proprietary Pine Script: **SuperTrend (10,3) + VWAP + ATR Trailing SL (No-Tuesday Filter)**")
    
    col1, col2, col3, col4 = st.columns([1.5, 1, 1.5, 1])
    with col1:
        test_asset = st.selectbox("Asset to Backtest", fno_base_universe)
    with col2:
        test_tf = st.selectbox("Timeframe", ["1", "5", "15"], index=1, format_func=lambda x: f"{x} Min")
    with col3:
        test_duration = st.slider("Lookback Period (Days)", min_value=5, max_value=60, value=30, step=5)
    with col4:
        st.write("")
        run_btn = st.button("🔬 Run Dixon Strategy", use_container_width=True, type="primary")
        
    if run_btn:
        st.markdown("---")
        with st.spinner(f"Fetching {test_duration} days of {test_tf}-Min tick data for {test_asset}..."):
            df = fetch_historical_data(fyers, get_spot_symbol(test_asset), test_tf, test_duration)
            
            if df is not None and not df.empty:
                with st.spinner("Compiling Pine Script Logic in Python..."):
                    trades_df, equity_curve = run_dixon_backtest(df)
                    
                if not trades_df.empty:
                    total_trades = len(trades_df)
                    wins = len(trades_df[trades_df['PnL'] > 0])
                    win_rate = (wins / total_trades) * 100 if total_trades > 0 else 0
                    total_points = trades_df['PnL'].sum()
                    
                    # --- METRICS UI ---
                    m1, m2, m3, m4 = st.columns(4)
                    with m1:
                        st.markdown(f"""<div style="background-color:#1a1c23; padding:15px; border-radius:6px; border: 1px solid #404654; text-align:center;">
                            <h4 style="margin:0; color:#888;">Total Trades</h4><h2 style="margin:0; color:#fff;">{total_trades}</h2></div>""", unsafe_allow_html=True)
                    with m2:
                        color = "#4caf50" if win_rate >= 40 else "#ff5252"
                        st.markdown(f"""<div style="background-color:#1a1c23; padding:15px; border-radius:6px; border: 1px solid {color}; text-align:center;">
                            <h4 style="margin:0; color:#888;">Dixon Win Rate</h4><h2 style="margin:0; color:{color};">{win_rate:.1f}%</h2></div>""", unsafe_allow_html=True)
                    with m3:
                        pnl_color = "#4caf50" if total_points > 0 else "#ff5252"
                        st.markdown(f"""<div style="background-color:#1a1c23; padding:15px; border-radius:6px; border: 1px solid {pnl_color}; text-align:center;">
                            <h4 style="margin:0; color:#888;">Net PnL (Points)</h4><h2 style="margin:0; color:{pnl_color};">{total_points:+.2f}</h2></div>""", unsafe_allow_html=True)
                    with m4:
                        st.markdown(f"""<div style="background-color:#1a1c23; padding:15px; border-radius:6px; border: 1px solid #1f77b4; text-align:center;">
                            <h4 style="margin:0; color:#888;">Strategy Type</h4><h2 style="margin:0; color:#1f77b4;">Trend Following</h2></div>""", unsafe_allow_html=True)
                    
                    st.markdown("### 📈 Cumulative Equity Curve (Points)")
                    st.area_chart(equity_curve, color="#1f77b4")
                    
                    st.markdown("### 📜 Detailed Trade Log (ATR Trailing)")
                    st.dataframe(trades_df.style.applymap(
                        lambda x: 'background-color: rgba(44, 160, 44, 0.2); color: #4caf50;' if x > 0 else 'background-color: rgba(214, 39, 40, 0.2); color: #ff5252;' if x < 0 else '', 
                        subset=['PnL']), use_container_width=True)
                else:
                    st.warning("No trades triggered. The strict timeframe (AM/PM) and Tuesday filters blocked all setups during this period.")
            else:
                st.error("Data Fetch Failed. Note: Fyers API allows max 30-60 days for 1-minute data. Reduce the Lookback Period and try again.")
